### ISSUE TITLE
How do I fix YUNG's API and Better Mineshafts not being able to load?

### ISSUE THREAD

**Issue by Sarsath** [YUNG-GANG/YUNGs-API#14]
https://imgur.com/a/XvXfLCT

latest: https://pastebin.com/ZEf12Kur

crash report: https://pastebin.com/2Dj4fEZM

What do I do?

**Comment by yungnickyoung** [comment]
You are using the 1.16 versions of my mods on Forge 1.17. Unfortunately, I do not have Forge 1.17 versions of my mods available for use.
