### ISSUE TITLE
[Fabric 1.18 branch] Trying to build from source fails

### ISSUE THREAD

**Issue by bravely-beep** [YUNG-GANG/YUNGs-API#16]
Looks like this is because I don't have your `ossrhUsername` and `ossrhPassword`

**Comment by bravely-beep** [comment]
```
A problem occurred evaluating root project 'YUNGs-API'.
> Could not get unknown property 'ossrhUsername' for Credentials [username: null] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.
```

**Comment by snibk** [comment]
I just encountered a problem with this today and the solution mentioned in NeuronRobotics/nrjavaserial#123 fixed it for me. Basically, replace the `credentials` field near the bottom of the build.gradle with
```
            credentials {
                username hasProperty('ossrhUsername')?ossrhUsername:''
                password hasProperty('ossrhPassword')?ossrhPassword:''
            }
```

Also submitted a PR: #30

**Comment by yungnickyoung** [comment]
Not sure why, but this fix does not work for me. Printing the same experssion (`hasProperty('ossrhUsername')?ossrhUsername:''`) indicates that it pulls the username/password properly, but for some reason I get a 401 when using this expression when publishing.
