### ISSUE TITLE
AE2 is unable to generate meteorites when added with YUNGs API

### ISSUE THREAD

**Issue by jdevang** [YUNG-GANG/YUNGs-API#22]
Adding YUNGs API with Applied Energestics 2 makes AE2 not generate any meteorite's. [Issue in AE2 github](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6023) Unsure whether its a conflict from AE2's side or from YUNGs API's side.

Minecraft Version - 1.18.1
Modloader - Fabric 
YUNGs API version - 36

**Comment by yungnickyoung** [comment]
Not really sure why this would be the case. The API itself doesn't really do any actual worldgen. I believe the only ways the API impacts worldgen at all is by:

- Adding support for entity post-processing for Jigsaw structures (https://github.com/yungnickyoung/YUNGs-API/blob/4a737ac35f7c398b438bcc90e7c31999af0abe0a/src/main/java/com/yungnickyoung/minecraft/yungsapi/mixin/EntityProcessorMixin.java)
- Increasing the hardcoded structure weight limit from 150 to 5000 (https://github.com/yungnickyoung/YUNGs-API/blob/4a737ac35f7c398b438bcc90e7c31999af0abe0a/src/main/java/com/yungnickyoung/minecraft/yungsapi/mixin/IncreaseStructureWeightLimitMixin.java)

Neither of these should have any tangible impact on structures from other mods.

**Comment by jdevang** [comment]
For a bit more context, we have BetterDungeons, BetterStrongholds, and Yungs Api. But removing any combination of the first two does not fix the issue of meteorite generation. While removing Yungs Api( and by extension, the first two as well) fixes the issue. 

I'll link your comment on the issue that's on AE2 GitHub as well to see if they can think of any reason these might stop their structure gen

**Comment by buhanec** [comment]
I tested a simple pack with:
-  `appliedenergistics2-10.1.0-beta.2`
-  `BetterDungeons-Fabric-1.18-1.0`
-  `BetterStrongholds-Fabric-1.18.1-1.0.1`
-  `cloth-config-6.2.57-fabric`
-  `fabric-api-0.46.6+1.18`
-  `YungsApi-1.18-Fabric-36`

I'm able to locate meteorites just fine. 

I've got a breaking pack too so might try a few more combinations before giving up.

Likely breaks in combination with some other mods, what else are you using @junglesucks?

[minecraft.log](https://github.com/yungnickyoung/YUNGs-API/files/8357970/minecraft.log)

---

Either of these two combinations work:

Terralith:
- `appliedenergistics2-10.1.0-beta.2`
- `fabric-api-0.46.6+1.18`
- `Terralith_v2.0.12_Fabric+Forge`

YUNG's API:
- `appliedenergistics2-10.1.0-beta.2`
- `fabric-api-0.46.6+1.18`
- `YungsApi-1.18-Fabric-36`

However one with both Terralith and YUNG's API will not generate meteorites:
- `appliedenergistics2-10.1.0-beta.2`
- `fabric-api-0.46.6+1.18`
- `Terralith_v2.0.12_Fabric+Forge`
- `YungsApi-1.18-Fabric-36`

Not the most useful log file, attached anyways.

[minecraft_failure.log](https://github.com/yungnickyoung/YUNGs-API/files/8357996/minecraft_failure.log)

**Comment by yungnickyoung** [comment]
Does this issue persist in 1.18.2? I don't plan on making changes to 1.18.1 moving forward.

**Comment by Khytwel** [comment]
No it's good now
