### ISSUE TITLE
1.18.2 Crash on load

### ISSUE THREAD

**Issue by Merith-TK** [YUNG-GANG/YUNGs-API#23]
https://mclo.gs/9Hi3Xvh < logs for my full modpack
https://mclo.gs/wJJPurW < logs of just fabric API and Yungs API

working on updating my vanillia modpack to 1.18.2 (mispelling intentional), and currently yungsapi is the only thing throwing errors at this time

running java 17

**Comment by yungnickyoung** [comment]
1.18.2 is not yet supported

**Comment by Merith-TK** [comment]
Well I would reccomend pinning this issue and leaving it open for people so they can see it at the top and not blindly open and issue lol
