### ISSUE TITLE
[Exit Code 1; FABRIC + FORGE] Possible incompatibility with 1.18 versions; Exit code 1 

### ISSUE THREAD

**Issue by Bazalbuilder** [YUNG-GANG/YUNGs-API#24]
Due to the recent release of 1.18, there is a different type of world generation than other mods can use, therefore it might be possible that YUNG's API is not actually compatible with 1.18, without re-coding the structure generation feature. This affects both the Forge and Fabric versions, which means it is physically impossible to run the API in 1.18 without modifying certain code. This also affects big mod libraries like BCLib (for BetterEnd+BetterNether). However, some mods like Terralith can work properly. I hope that a possible fix can come soon.

Note: When there is an Exit Code 1 crash, there is no crash log provided.

**Comment by yungnickyoung** [comment]
1.18.2 is not yet supported. The only mods available right now for 1.18.2 are the API and Paxi and they may not be completely functional. Full ports will be coming soon
