### ISSUE TITLE
Forge 1.18.1/1.18.2 @ModifyConstant conflict between yungsapi and repurposed_structures

### ISSUE THREAD

**Issue by WolfBV** [YUNG-GANG/YUNGs-API#25]
[pool-3-thread-1/WARN]: @ModifyConstant conflict. Skipping yungsapi.mixins.json:IncreaseStructureWeightLimitMixin->@ModifyConstant::yungsapi_increaseWeightLimit(I)I with priority 1000, already redirected by repurposed_structures.mixins.json:structures.StructurePoolMixin->@ModifyConstant::repurposedstructures_increaseWeightLimitDev(I)I with priority 1000

1.18.1
.
YungsApi-1.18.1-Forge-26
repurposed_structures_forge-4.2.11+1.18.1
forge version 39.1.2
.

1.18.2
.
YungsApi-1.18.2-Forge-2.0.7
repurposed_structures_forge-5.0.4+1.18.2
forge version 40.0.18
.

**Comment by yungnickyoung** [comment]
This is just a warning because we both apply a mixin with the same behavior. It should work as intended.
