### ISSUE TITLE
Bound must be positive game crashes when loading world 1.16.5 forge

### ISSUE THREAD

**Issue by UwUsheep** [YUNG-GANG/YUNGs-API#27]
here is the crash
[crash-2022-04-03_14.00.33-server.txt](https://github.com/yungnickyoung/YUNGs-API/files/8405898/crash-2022-04-03_14.00.33-server.txt)

**Comment by NixityNull** [comment]
I am having a similar issue that also seems to be effecting other structure mods.
[crash-2022-04-30_13.21.52-server.txt](https://github.com/YUNG-GANG/YUNGs-API/files/8597536/crash-2022-04-30_13.21.52-server.txt)

**Comment by NixityNull** [comment]
I removed yung's api and all associated mods and it still crashed, so i don't believe this is necessarily the cause

**Comment by yungnickyoung** [comment]
It's impossible to tell from these logs alone, but this often happens because structure mods offer settings for a minY and maxY. If you set the minY to be greater than the maxY (which makes no sense), this crash is commonly the result. Double check all your mod configs.
