### ISSUE TITLE
Critical injection failure: Constant modifier method fastSpawn(I)I in yungsapi.mixins.json:MinecraftServerMixin failed injection check

### ISSUE THREAD

**Issue by Dutchs** [YUNG-GANG/YUNGs-API#31]
Version: YungsApi-1.18.2-Forge-2.0.7

This is a crashing issue when using this mod with: [configurablespawnchunks](https://www.curseforge.com/minecraft/mc-mods/configurablespawnchunks)
I suspect fastSpawn is a test mixin left in the release build on accident?

**Comment by Dutchs** [comment]
log: https://gist.github.com/Dutchs/3fd39368f0e959690d3e5dfb21d79f89

**Comment by yungnickyoung** [comment]
Oops, forgot to push this fix. Will upload it later today.

**Comment by yungnickyoung** [comment]
Try v2.0.8 and see if it works for ya

**Comment by Dutchs** [comment]
That does appear to fix this issue, Thanks!
