### ISSUE TITLE
Multiloader 1.19 gradlew build fail

### ISSUE THREAD

**Issue by GlitchyTechOffical** [YUNG-GANG/YUNGs-API#33]
[Multiloader 1.19 Active branch] every single time i do the gradlew build command on command promt on the folder the daemon fails the build

**Comment by yungnickyoung** [comment]
Prety sure this is the same thing as #16 , but to confirm you'll need to provide the actual error log

**Comment by GlitchyTechOffical** [comment]
Yung here

A problem occurred evaluating project ':Common'.
 Could not get unknown property 'ossrhUsername' for Credentials [username: null] of type org.gradle.internal.credentials.DefaultPasswordCredentials_Decorated.

**Comment by yungnickyoung** [comment]
Should be fixed with latest commit. Please open a new report if the issue persists.
