### ISSUE TITLE
Relocate Reflections (and Javassist) or depend on it with include("org.reflections:...")

### ISSUE THREAD

**Issue by Cypher121** [YUNG-GANG/YUNGs-API#34]
Causes conflict with [Light Overlay](https://modrinth.com/mod/light-overlay).

In general, when including code from other libraries without use of Fabric/Quilt's `include` JiJ configuration, the package should be changed to something unique to the mod.

As this API copies code from org.reflections:reflections without changing the package, it crashes alongside light overlay, which `include`s an older version of the same library lacking one of the used methods.

Change the package to something like `com.yungnickyoung.minecraft.yungsapi.included.org.reflections` to fix. 

Alternatively, as this seems to be a fabric-only dependency, go the recommended route and include the actual jar to let Fabric do the version handling:

```
dependencies {
    implementation("org.reflections:reflections:0.10.2")
    include("org.reflections:reflections:0.10.2")
}
```

Same applies to Javassist.

**Comment by yungnickyoung** [comment]
Thanks, I totally forgot to address this. Will probably just move it to a fabric include like you said

**Comment by yungnickyoung** [comment]
Fixed in the latest releases.
