### ISSUE TITLE
Crash with 1.16.5 forge version, happens while playing a while in a world (Singleplayer)

### ISSUE THREAD

**Issue by TheOtherworldly** [YUNG-GANG/YUNGs-API#46]
This is not a twilight forest and optifine issue. Ive tested everything, and ive found that the crash occurs only with your api mod installed (And of course other yungs mods). Exit code is 1 and there is no generated crash report so here is my log
https://paste.gg/p/anonymous/dadacb88a0d04e41a29e0ef1571fe67f
Please help, id love to use your mods, but right now they are fatal :/

**Comment by SiverDX** [comment]
> The NVIDIA OpenGL driver has encountered an out of memory error

u got any more of that ram

**Comment by loccocmagnotta** [comment]
same problem

**Comment by loccocmagnotta** [comment]
try using multimc cause i have no idea this existed until i switch to minecraft launcher

**Comment by yungnickyoung** [comment]
Sorry I never saw this! But I highly doubt this was an error on my end considering other users have been able to use the mods on 1.16.5 just fine.
