### ISSUE TITLE
Unable to open MC

### ISSUE THREAD

**Issue by dyscontrol** [YUNG-GANG/YUNGs-API#47]
Simply unable to open MC, giving this log whenever I attempt to:
[crash-2023-06-08_23.33.53-client.txt](https://github.com/YUNG-GANG/YUNGs-API/files/11702046/crash-2023-06-08_23.33.53-client.txt)

**Comment by yungnickyoung** [comment]
Looks like the config for Better Desert Temples might have corrupted it. Delete the config file and try running the game again
