### ISSUE TITLE
Yung's API and Thread Locks with Chunky

### ISSUE THREAD

**Issue by Sniffity** [YUNG-GANG/YUNGs-API#48]
Hey!

What follows is a somewhat extensive bug report for a possible thread lock issue relating to Yung's API and Chunky. This concerns **Minecraft 1.19.2 and Forge Version 43.2.0**

I was recently trying to pregen a 1.19.2 world with Chunky. I started running into an issue where the Chunky task would just freeze. The server wouldn't necessarily crash, but the task itself was frozen and the server was also unresponsive. 

To give full details, this first happened midway through an overworld generation task. I do note that upon shutting down the server, restarting and attempting the same task it appeared to progress further than before, although it did get locked again further on down the line.

Eventually the overworld generation task finished. At this point I managed to get in touch with Chunky's developer. They suggested I run a stack trace to identify what, exactly, was locking the thread. 

I proceeded to start a new Chunky generation task, this time for the Nether. The thread lock here occurred immediately upon starting the task. I was able to get the stack trace for this, which showed Yung's API in the trace. Just to be certain, I restarted the server and repeated the process, obtaining a second stack trace which also showed YUNG's API.

I am attaching both stack traces previously mentioned. 
Stack Trace 1: https://justpaste.it/cy1gp
Stack Trace 2:  https://justpaste.it/c1y98

Additionally, I am including a full list of the mods I was using:
https://justpaste.it/cx4hk

Finally, I was also using the following datapacks:
-Terralith
-Structory
-Continents
-Incendium
-Nullscape

I hope this report is helpful - I tried to gather as much data as possible! 

If any more details are needed, please do feel free to contact me on Discord, I am part of your community there (sniffity)!

All the best!

**Comment by yungnickyoung** [comment]
Hey, thanks for the extensive report! The stack trace just shows my API invoking normal vanilla methods of world generation, so I would suspect this is an issue with Chunky. I don't think my custom Jigsaw piece type does anything significantly different from vanilla's

**Comment by pop4959** [comment]
Just as a follow-up here, @Sniffity discovered shortly after posting here that the issue was still prevalent. It's not going to be an issue with Chunky or Yung-API though. As with Yung, Chunky does not overwrite any vanilla methods, it simply requests chunks from the server.

It's not unusual for this issue to be caused by conflicting mods, but blame is clearly misplaced here - just coincidentally the API did show up both times the server hung.

Please feel free to resolve this issue as invalid.
