### ISSUE TITLE
Update for 1.20?

### ISSUE THREAD

**Issue by allanonmage** [YUNG-GANG/YUNGs-API#49]
I'm checking on the mods I've included in my modpack to see where development is.  I told my players that it might be several months after 1.20 is released before all our mods are updated.  Will you be updating your mods?  Do you have an ETA when you will be adding support for the later versions?  Are your 1.20 updates currently Patreon only?

**Comment by AuroraDoesCode** [comment]
He currently has them Patreon Only.

**Comment by JTModel3** [comment]
Will they be opened to the public eventually?

**Comment by Bwapt** [comment]
Yes, this is what is planned. But when will it be release publicly ? Maybe in a few days/weeks. Nobody but YUNG can tell.

**Comment by ProsperCraft** [comment]
Thank you for asking the question, I came looking for the same thing.

**Comment by yungnickyoung** [comment]
The 1.20 versions of my mods are currently available on Patreon. I'm not sure when they will be publicly released, but hopefully not too much longer. That being said, all of my mods have public 1.20 branches on GitHub that you can build from if you're able to!

**Comment by IINovaIl** [comment]
if i can get them build will they work on 1.20.1?

**Comment by IINovaIl** [comment]
ok so funny thing i got yung api to build but when i try to build any of his other mods i get errors saying it use deprecated gradle lines or something
