### ISSUE TITLE
1.20.2 & soon to be 1.20.3?

### ISSUE THREAD

**Issue by TheRubyGames** [YUNG-GANG/YUNGs-API#54]
I am a host of a smp server and wanna add in yung's better structures but it seems the .1 versions do not work with .2. Could we get an update for .2 and eventually ,3 please?

**Comment by yungnickyoung** [comment]
At this point I may just wait until 1.20.3 releases to port my mods, since Mojang is already putting out snapshots. But either way once I've ported all my mods I'll post an announcement on the [Discord](https://discord.gg/yung)

**Comment by unilock** [comment]
For what it's worth, I ported YUNG's API to 1.20.2 here: https://github.com/unilock/YUNGs-API/tree/1.20.2

I only touched the Fabric version, as I don't use Forge, and the port was originally only for my own (private) usage anyway. I also fear the code may be temperamental, but it seems to be working fine so far. Maybe someone else will find it useful?

**Comment by TheRubyGames** [comment]
Thank you! I appreciate it

**Comment by JuceInUse** [comment]
Hey Yung! I understand wanting to wait, but if there's a working 1.20.2 PR, it'd be awesome if you could push it! I am currently hosting a 1.20.2 Aternos Geyser server and we would love to use your mods! Sadly, updating all the mods to 1.20.3 will take a bit, so it'd be nice if we didn't have to sweat it
