### ISSUE TITLE
[Fabric 1.20.1] Crash on world gen with c2me and Additional Additions

### ISSUE THREAD

**Issue by Hexblood** [YUNG-GANG/YUNGs-API#59]
First off I see both AA and yungsapi listed in the log so I am reporting to both.

Minecraft: 1.20.1
Mod Loader: Fabric 0.15.3
Yungs API version: 4.0.2

Crash seems to occur after world is built or nearly done and before loading the player in the world.

As seen in the report c2me says this is probably not their bug and to report to other mods.

Crash-Report: https://pastebin.com/J9g4ZVES

**Comment by yungnickyoung** [comment]
Sorry for the late response. This is on AA's side, as they are using the Server random in their WanderingTraderMixin, when they should be using the entity's random. Please let them know!
