### ISSUE TITLE
chunk generation errors in 1.19.2

### ISSUE THREAD

**Issue by Kinsypoo** [YUNG-GANG/YUNGs-API#61]
[crash-2024-01-07_00.03.39-server.txt](https://github.com/YUNG-GANG/YUNGs-API/files/13852207/crash-2024-01-07_00.03.39-server.txt)

ive gotten this a few times any ideas on a reason? it always references yungs api seems to happen at random

**Comment by yungnickyoung** [comment]
Not too sure what's causing this. I'm pretty sure I'm calling a normal vanilla function in an expected place, so it's likely a compat issue with another mod. Do you have any server-side performance mods?

**Comment by Kinsypoo** [comment]
hey i stopped hosting the server i think i had a couple but i cant remember
which ones sorry.

**Comment by yungnickyoung** [comment]
Closing due to lack of info
