### ISSUE TITLE
windows defender warning

### ISSUE THREAD

**Issue by Rogenar** [YUNG-GANG/YUNGs-API#65]
[1.20.4] When I download YUNG's API v4.4.2 (Fabric) version, windows defender issues a warning and deletes the file

**Comment by LivingSkeleton11** [comment]
I'm getting it as well. It says there's a Trojan script in the mod, specifically "Trojan:Script/Wacatac.H!ml"

**Comment by MrPlayerYork** [comment]
same here

**Comment by dretez** [comment]
Same here

**Comment by AnonymousCrossOG** [comment]
I am also getting that!

**Comment by yungnickyoung** [comment]
Just a false positive from Windows Defender. Every now and then a mod gets caught with a false positive Wacatac, I know it happened to Create last year. Is this still happening with the latest version of Defender?

**Comment by dretez** [comment]
I can confirm that Defender no longer flags the file as a virus.
