### ISSUE TITLE
1.20.2 Support

### ISSUE THREAD

**Issue by user10072023github** [YUNG-GANG/YUNGs-API#66]
Hi guys, thanks for making this mod. Looks like 1.20.2 and 1.20.3 was skipped.  I standardized on 1.20.2 a ways back and don't want to move up until there's something really really compelling since a couple of my favorite worlds and progress was done in 1.20.2 and the corresponding version of the mods that were out. Please please please consider backporting to 1.20.2 for those like me. Thanks again

**Comment by yungnickyoung** [comment]
Sorry, but I will be skipping 1.20.2 and 1.20.3
