### ISSUE TITLE
Do you pretend to update other mods for 1.20.1?

### ISSUE THREAD

**Issue by CanecaKun** [YUNG-GANG/YUNGs-API#69]
I noticed most replies / labels were on 2021, are you still developing mods like the better portals that is severely outdated?
Decided to type here since its more recently been updated

**Comment by Sketano** [comment]
lol i dont care about this "issue" but 69 lol

**Comment by yungnickyoung** [comment]
Any mods that I haven't updated to 1.20.1 are abandoned, including Better Portals and Better Caves
