### ISSUE TITLE
When is 1.21 support going to be officially packaged?

### ISSUE THREAD

**Issue by imeesa** [YUNG-GANG/YUNGs-API#71]
I am currently running a 1,21 server (private) for me and some friends. I would like to use several of the YUNG's better group of mods, however as there is no packaged version available on modrinth (which is how i update the server's mods), I have to compile from source which sometimes can break Modrinth's auto-update.

When is official 1.21 support planned?

**Comment by opee2012** [comment]
Is asking for 1.21 support a bug or other issue with the code? This is not the place to ask these questions nor will this question be answered as their is no ETA or planned release date for 1.21.

**Comment by imeesa** [comment]
> Is asking for 1.21 support a bug or other issue with the code?

 This is the only place where this question can be asked...
 
> This is not the place to ask these questions nor will this question be answered as there is no ETA or planned release date for 1.21.

Woah, woah. You aren't YUNG, and you can't know if he will answer. This question itself is inquiring about the existence of support.

I've been having major issues with building YUNG's Better End Islands for 1.21, so I asked here.

There was no need for the passive-agressiveness of your comment.

**Comment by opee2012** [comment]
More information on your inquiry is available on his Discord server.

**Comment by imeesa** [comment]
uh oops
https://github.com/YUNG-GANG/YUNGs-Better-End-Island/pull/43
