### ISSUE TITLE
Fabric cannot find API

### ISSUE THREAD

**Issue by FabricStuff** [YUNG-GANG/YUNGs-API#8]
When I launch Minecraft Fabric, I get a crash issue that says it "Could not find required mod: yungsapi requires {fabric @ [>=0.25.0]}". But I already have the latest ver. installed to my mods folder.

**Comment by yungnickyoung** [comment]
Double check. That is a message from the fabric loader itself, not my mod. So you may have accidentally downloaded the wrong version, or not placed it in your mods folder.
